spring:
  profiles:
    active: dev
  server:
    port: 8080
  security:
    user:
      name: admin
      password: 123456
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/testDatabase}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:123456}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 10
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update