spring:
  profiles:
    active: dev
  server:
    port: 8080
  security:
    user:
      name: admin
      password: 123456
  datasource:
    url: jdbc:postgresql://localhost:5432/testDatabase
    username: postgres
    password: 123456
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
      show-sql: true